services:
  db:
    image: postgres
    hostname: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
  
  scheduler:
    image: shubhamgoel23/scheduler:2.0
    hostname: scheduler
    deploy:
      replicas: 3
    expose:
     - 8080
    environment:
     - postgres=postgres
     - showsql=false
    restart: unless-stopped
    depends_on:
     - postgres
  nginx:
   image: nginx:latest
   volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
   depends_on:
    - scheduler
   ports:
    - 8080:8080